### ISSUE TITLE
Not working anymore (Ubuntu 20.04, Ulauncher v5.8.0)

### ISSUE THREAD

**Issue by dferrandizmont** [sergius02/ulauncher-colorconverter#5]
I don't know if I messed up something when updating the extension but right now all the keywords are **torgb**

![image](https://user-images.githubusercontent.com/6375953/101160310-19d9d080-362f-11eb-9c8b-05f50d246ec0.png)

and when I try to convert a color doesn't work at all

![image](https://user-images.githubusercontent.com/6375953/101160534-7f2dc180-362f-11eb-84af-bb35665631ca.png)
![image](https://user-images.githubusercontent.com/6375953/101160679-b8663180-362f-11eb-8122-7a0f0c941932.png)
![image](https://user-images.githubusercontent.com/6375953/101160729-cddb5b80-362f-11eb-94f1-c9d2563a929c.png)

nothing happens, tried to uninstall and install it again but same behavior.

Thanks! :+1:

**Comment by sergius02** [comment]
Hi!

I had to change the keywords to implement more formats easy

The configuration now should be like this
![colorconverter](https://user-images.githubusercontent.com/10380412/101200779-0fd3c400-3667-11eb-85ea-732d9100aab7.png)

Change the keywords as are in the screenshot and it should be solved

**Comment by dferrandizmont** [comment]
Thanks for the quick reply @sergius02 , I'll give it a try on Monday 'cause I'm using it on my work laptop. 👍

**Comment by sergius02** [comment]
Hi!

I updated the extension right now, you should be able now to change the keywords to what you want, and the extensions should work

**Comment by dferrandizmont** [comment]
Hey! 

Now its working like a charm, thank you so much @sergius02 :1st_place_medal:
